import Part
from FreeCAD import Vector
boxshape=Part.makeBox(93,64,30,Vector(-4,-4,-8))
cutout=Part.makeBox(87,58,30,Vector(-1,-1,-5))
pibase=boxshape.cut(cutout)
leftsidecut=Part.makeBox(20,42,30,Vector(-10,2,-4))
pibase=pibase.cut(leftsidecut)
hdmicut=Part.makeBox(18,20,30,Vector(35,-10,-2))
avcut=Part.makeBox(33,20,30,Vector(38,50,0))
usbcut=Part.makeBox(20,38,30,Vector(80,1,-2))
pibase=pibase.cut(hdmicut)
pibase=pibase.cut(avcut)
pibase=pibase.cut(usbcut)
lidcut=Part.makeBox(90,61,10,Vector(-2.5,-2.5,19))
pibase=pibase.cut(lidcut)
boss1=Part.makeCylinder(3.5,7,Vector(25.5,18,-7))
boss2=Part.makeCylinder(3.5,7,Vector(80,43.5,-7))
pibase=pibase.fuse(boss1)
pibase=pibase.fuse(boss2)
Part.show(pibase)
